name: 'Conflictor'
description: 'Utility that analyzes pull requests and conflicts between them'
branding:
  icon: git-pull-request
  color: yellow
inputs:
  repository:
    description: 'Repository full name'
    required: true
  deploy-label:
    description: 'Deploy label'
    required: true
runs:
  using: 'docker'
  image: 'dockerfile'
  env:
    REPOSITORY_FULL_NAME: ${{ inputs.repository }}
    # PULL_REQUEST_LABEL_CONFLICT: ${{ inputs.label-conflict }}
